Extension Types
jagpreetstamber/azure-rest-api-specs pull request #4
Opened 2023-04-04 21:12 UTC by nikkomiu

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [ ] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. If updating an existing version, please select the specific langauge SDKs and CLIs that must be refreshed after the swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No refresh required for updates in this PR

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist 

> **Applicability**: :warning: 
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs 
> - Adding new properties 
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [ ] Check this box if any of the following apply to the PR so that label "WaitForARMFeedback" will be added automatically to begin ARM API Review. Failure to comply may result in delays to the manifest.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits.

- [ ] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If any of the following scenarios apply to the PR, request approval from the Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 
- [ ] Removing API(s) in a stable version
- [ ] Removing properties in a stable version
- [ ] Removing API version(s) in a stable version
- [ ] Updating API in a stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

2023-04-06 03:22 UTC, NarayanThiru requested changes

2023-04-06 03:22 UTC, NarayanThiru commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensions.json
> +            "description": "Release train",
Is ReleaseTrain a parameter to this api?  Do you plan on filtering based on releaseTrain?  If so, explain this in the description of this parameter.

2023-04-06 03:22 UTC, NarayanThiru commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensions.json
> +            "in": "query",
Similar to above question.  Pl. explain usage in the description.

2023-04-06 03:22 UTC, NarayanThiru commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensions.json
> +            "name": "offerId",
Will OfferId be used as a parameter?  Explain in description.  Make sure to get this reviewed by the MarketPlace crew

2023-04-06 03:22 UTC, NarayanThiru commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensions.json
> +            "in": "query",
Similar to above question.  Pl. explain usage in the description, if this will be used

2023-04-06 03:22 UTC, NarayanThiru commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensions.json
> +          "Extensions",
Replace Extensions tag with ExtensionTypes, as this is not extensions resource.  Update ClusterExtensions with ClusterExtensionTypes.

2023-04-06 03:22 UTC, NarayanThiru commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensions.json
> +          "Extensions",
Replace Extensions tag with ExtensionTypes, as this is not extensions resource.  Update ClusterExtensions with ClusterExtensionTypes.

2023-04-06 03:22 UTC, NarayanThiru commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensions.json
> +    "/subscriptions/{subscriptionId}/providers/Microsoft.KubernetesConfiguration/locations/{location}/extensionTypes/{extensionName}": {
It should  be extensionTypeName

2023-04-06 03:22 UTC, NarayanThiru commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensions.json
> +            "$ref": "#/parameters/ExtensionNameParameter"
This must be ExtensionTypeNameParameter

2023-04-06 03:22 UTC, NarayanThiru commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensions.json
> +    "/subcriptions/{subscriptionId}/providers/Microsoft.KubernetesConfiguration/locations/{location}/extensionTypes/{extensionName}/versions": {
This must be extensionTypeName

2023-04-06 03:22 UTC, NarayanThiru commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensions.json
> +          "Extensions",
Replace Extensions tag with ExtensionTypes, as this is not extensions resource.  Update ClusterExtensions with ClusterExtensionTypes.

2023-04-06 03:22 UTC, NarayanThiru commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensions.json
> +            "$ref": "#/parameters/ExtensionNameParameter"
This must be ExtensionTypeNameParameter

2023-04-06 03:22 UTC, NarayanThiru commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensions.json
> +            "type": {
Do we have a type for extensionType?

2023-04-06 15:22 UTC, nikkomiu commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensions.json
> +            "type": {
I didn't see a type for ExtensionType

2023-04-06 15:25 UTC, nikkomiu commented
@NarayanThiru I updated based on your comments. It's going to be a bit of a pain because I also switched it to its own file since it seems to make more sense that way. I can always move it back if you don't like it this way though.

2023-04-06 15:36 UTC, kulalking commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensionTypes.json
> +          }
we dont need this right ?

2023-04-06 15:37 UTC, kulalking commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensionTypes.json
> +              "$ref": "#/definitions/ExtensionTypesList"
>ExtensionTypesList [](http://example.com/codeflow?start=37&length=18)

can you please add this also part of the review. this is what  even then ARM swagger reviewers will ask you to do. it helps to review faster.

2023-04-06 15:39 UTC, kulalking commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensionTypes.json
> +          "description": "List of Extension Types within a Kubernetes cluster."
>List of Extension Types within a Kubernetes cluster. [](http://example.com/codeflow?start=26&length=52)

List of ext types (please remove within a kub cluster)

2023-04-06 15:42 UTC, kulalking commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensionTypes.json
> +            "properties": {
>properties [](http://example.com/codeflow?start=13&length=10)

Even these details we are asking publishers to provide is it?

2023-04-06 15:43 UTC, kulalking commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensionTypes.json
> +                  "key": {
>key" [](http://example.com/codeflow?start=19&length=4)

do we need to have type also here ?

2023-04-06 15:43 UTC, kulalking commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensionTypes.json
> +                  "key": {
>"key" [](http://example.com/codeflow?start=18&length=5)

do we need type also here?

2023-04-06 15:44 UTC, kulalking commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensionTypes.json
> +            "id": {
> "id": [](http://example.com/codeflow?start=11&length=6)

what is this? i think we can remove this unless you have something in your mind.

2023-04-06 15:45 UTC, nikkomiu commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensionTypes.json
> +          }
I thought they said that they still wanted it to be on there. We can ask them later today to verify.

2023-04-06 15:45 UTC, nikkomiu commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensionTypes.json
> +            "properties": {
Yea, I believe so. We can double check later today.

2023-04-06 15:45 UTC, kulalking commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensionTypes.json
> +            "type": {
>"type": [](http://example.com/codeflow?start=12&length=7)

what is type represents ?

2023-04-06 15:49 UTC, kulalking commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensionTypes.json
> +    "ExtensionType": {
>ExtensionType [](http://example.com/codeflow?start=5&length=13)

we need Publisher, Description, IsSystemExtension(check with Arif is this required),  planinfo (check with arif)

2023-04-06 15:49 UTC, kulalking requested changes
:clock1:

2023-04-06 15:50 UTC, kulalking commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensionTypes.json
> +          }
they? is that Arif? lets sync

2023-04-06 15:52 UTC, nikkomiu commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensionTypes.json
> +            "type": {
Obviously, type represents the type of the extension type 😝. I removed it. Not sure why it was there either...

2023-04-06 15:56 UTC, kulalking commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensionTypes.json
> +            "$ref": "./examples/ListExtensionTypesByLocation.json"
>ListExtensionTypesByLocation [](http://example.com/codeflow?start=32&length=28)

can you please add this also part of the review. it helps to review even for ARM team.

2023-04-06 15:57 UTC, kulalking commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensionTypes.json
> +        "parameters": [
>parameters [](http://example.com/codeflow?start=9&length=10)

apiversion parameter is missing here.

2023-04-06 18:11 UTC, kulalking commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensionTypes.json
> +    "/subscriptions/{subscriptionId}/providers/Microsoft.KubernetesConfiguration/locations/{location}/extensionTypes/{extensionTypeName}": {
>locations/{location} [](http://example.com/codeflow?start=81&length=20)

why do we need this ?

2023-04-06 18:12 UTC, kulalking commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensionTypes.json
> +    "ExtensionType": {
>ExtensionType [](http://example.com/codeflow?start=5&length=13)

do we need to show list of supported regions as well ?

2023-04-06 18:13 UTC, nikkomiu commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensionTypes.json
> +    "/subscriptions/{subscriptionId}/providers/Microsoft.KubernetesConfiguration/locations/{location}/extensionTypes/{extensionTypeName}": {
This is going to be a "location based" route for the extension types. There was another one that was discussed that was "cluster-based" but I want to see if that one is actually going to be relevant since extension types isn't actually cluster based.

2023-04-06 18:15 UTC, kulalking commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensionTypes.json
> +    "/subcriptions/{subscriptionId}/providers/Microsoft.KubernetesConfiguration/locations/{location}/extensionTypes/{extensionTypeName}/versions": {
>locations/{location} [](http://example.com/codeflow?start=80&length=20)

can we move this to query parameter, we can discuss this with PM if required

2023-04-06 18:17 UTC, kulalking commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensionTypes.json
> +    "/subcriptions/{subscriptionId}/providers/Microsoft.KubernetesConfiguration/locations/{location}/extensionTypes/{extensionTypeName}/versions": {
>versions [](http://example.com/codeflow?start=136&length=8)

can we please add the section for query parameters and add the all the supported query parameters, release train , location, plan info check with arif

2023-04-06 18:18 UTC, nikkomiu commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensionTypes.json
> +    "/subcriptions/{subscriptionId}/providers/Microsoft.KubernetesConfiguration/locations/{location}/extensionTypes/{extensionTypeName}/versions": {
So you're saying that you want the route to be /subcriptions/{subscriptionId}/providers/Microsoft.KubernetesConfiguration/extensionTypes (and all routes sub-routes to that)?

2023-04-06 18:19 UTC, kulalking commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensionTypes.json
> +  "swagger": "2.0",
>swagger [](http://example.com/codeflow?start=3&length=7)

you have missed the get extension types based on cluster types, is that dropped ?

2023-04-06 18:21 UTC, nikkomiu commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensionTypes.json
> +    "/subcriptions/{subscriptionId}/providers/Microsoft.KubernetesConfiguration/locations/{location}/extensionTypes/{extensionTypeName}/versions": {
Yea, they should all be there. Versions doesn't have query params but the other routes where they're applicable have them listed. https://github.com/jagpreetstamber/azure-rest-api-specs/pull/4/files/c0f3e9a24d61150f6279e04ffb591a1c6bd4cb17#diff-7ae1ee61c9a7e9c57b4668dbff49e25f84c1c6fafc5417eaae270190144386e2R57-R84

2023-04-06 20:31 UTC, nikkomiu commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensionTypes.json
> +  "swagger": "2.0",
Added those routes

2023-04-06 21:33 UTC, kulalking commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensionTypes.json
> +    "/subscriptions/{subscriptionId}/providers/Microsoft.KubernetesConfiguration/locations/{location}/extensionTypes": {
>locations/{location} [](http://example.com/codeflow?start=81&length=20)

can we move it to query parameter

2023-04-06 22:25 UTC, kulalking commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensionTypes.json
> +            "$ref": "../../../../../common-types/resource-management/v3/types.json#/parameters/LocationParameter"
>LocationParameter [](http://example.com/codeflow?start=95&length=17)

release train

2023-04-06 22:26 UTC, kulalking commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensionTypes.json
> +          },
not required

2023-04-07 15:44 UTC, nikkomiu commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensionTypes.json
> +                  "key": {
I can add this if you'd like. I guess even if it doesn't get used (initially) it probably won't be a big deal...and we could just default everything to string 😛

2023-04-07 17:59 UTC, nikkomiu commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensionTypes.json
> +                  "key": {
I went back and looked at my notes from the first meeting we had. They didn't want to have a type property. They thought it would be overkill.

2023-04-07 20:48 UTC, kulalking commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensionTypes.json
> +          },
we don't need this.

2023-04-07 20:49 UTC, kulalking commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensionTypes.json
> +          },
we dont need this as well

2023-04-07 20:53 UTC, NarayanThiru commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensionTypes.json
> +    "title": "ExtensionsClient",
>ExtensionsClient [](http://example.com/codeflow?start=14&length=16)

Change this to ExtensionTypesClient

2023-04-07 20:54 UTC, NarayanThiru commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensionTypes.json
> +            "description": "Filter results by Publisher ID of a marketplace extension",
>extension [](http://example.com/codeflow?start=76&length=9)

Extension Type

2023-04-07 21:02 UTC, NarayanThiru commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensionTypes.json
> +    "ExtensionTypeVersion": {
>ExtensionTypeVersion [](http://example.com/codeflow?start=5&length=20)

This is misleading - as it contains ReleaseTrain as well.  May be a name like ExtensionTypeVersionsByReleaseTrain would be better, no?

2023-04-07 21:09 UTC, NarayanThiru commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensionTypes.json
> +        "description": "List Extension Types for the cluster.",
>List Extension Types for the cluster [](http://example.com/codeflow?start=24&length=36)

Is this ExtensionTypes of extensions 'installed' in the cluster or that 'can be installed' in the cluster?  If latter, how do you determine what extensions can be installed?  Explain that in the description, so it is clear what the intent of this api is.  This will go in the public documentation of our spec!

2023-04-07 21:11 UTC, NarayanThiru commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensionTypes.json
> +            "description": "Filter results by Offer ID of a marketplace extension",
>extension [](http://example.com/codeflow?start=72&length=9)

Extension Type

2023-04-07 21:16 UTC, NarayanThiru requested changes

2023-04-07 21:16 UTC, NarayanThiru commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensionTypes.json
> +      "get": {
We will need a GET of Version as well.  This will used to check if a version exists or not - we can't expect the client to do a list and go through it to check if it exists

2023-04-07 21:21 UTC, NarayanThiru commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensionTypes.json
> +  "definitions": {
>definitions [](http://example.com/codeflow?start=3&length=11)

Move these types under common

2023-04-07 21:23 UTC, NarayanThiru commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensionTypes.json
> +                "description": "Marketplace Extension Type Publisher ID."
>Marketplace Extension Type Publisher ID [](http://example.com/codeflow?start=32&length=39)

Reword this to "Publisher Id of the Marketplace Extension"

2023-04-07 21:24 UTC, NarayanThiru commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensionTypes.json
> +          "planInfo": {
>planInfo [](http://example.com/codeflow?start=11&length=8)

Add a description "Only for Marketplace Extension Types"

2023-04-07 21:27 UTC, NarayanThiru commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensionTypes.json
> +            "description": "The list of cluster types of the extension type.",
>The list of cluster types of the extension type [](http://example.com/codeflow?start=28&length=47)

Reword to "Cluster Types supported for this Extension Type"

2023-04-07 21:27 UTC, NarayanThiru commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensionTypes.json
> +              "description": "The default scope of the extension type.",
>extension type [](http://example.com/codeflow?start=55&length=14)

Add "This scope will be used if the user does not provide a scope while creating an extension"

2023-04-07 21:29 UTC, NarayanThiru commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensionTypes.json
> +          "description": "The list of versions of the extension type.",
>extension type. [](http://example.com/codeflow?start=54&length=15)

expand this to say "...for this Release Train"

2023-04-07 21:32 UTC, NarayanThiru commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/stable/2023-05-01/extensionTypes.json
> +          "description": "List of Extension Type Versions for an Extension Type."
>Type Versions for an Extension Type. [](http://example.com/codeflow?start=44&length=36)

You need to clarify that this list is Versions per ReleaseTrain

2023-04-07 22:05 UTC, nikkomiu commented
Add Query Parameter to Location-based routing for `extensionType`

2023-04-10 19:15 UTC, kulalking commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/preview/2023-05-01-preview/extensionTypes.json
> +          },
remove

2023-04-10 19:27 UTC, kulalking commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/preview/2023-05-01-preview/extensionTypes.json
> +          },
remove this

2023-04-11 17:12 UTC, kulalking commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/preview/2023-05-01-preview/extensionTypes.json
> +            "name": "publisherId",
>publisherId [](http://example.com/codeflow?start=21&length=11)

plan id ? question

2023-04-12 18:52 UTC, NarayanThiru commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/preview/2023-05-01-preview/extensionTypes.json
> +    "/subcriptions/{subscriptionId}/providers/Microsoft.KubernetesConfiguration/locations/{location}/extensionTypes/{extensionTypeName}/versions": {
>"/subcriptions [](http://example.com/codeflow?start=4&length=14)

We'll need a new api that gives the latest version for a given ExtensionType+ReleaseTrain+ClusterType

2023-04-13 18:12 UTC, ponatara commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/preview/2023-05-01-preview/examples/GetExtensionTypeVersion.json
> +            "appliances": [
Can you confirm that we'll filter to show only the unsupported versions for a cluster type if the request is in context of a cluster type?

2023-04-13 18:15 UTC, ponatara commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/preview/2023-05-01-preview/examples/GetExtensionType.json
> +          "shouldCreateIdentity": true,
Did you get a chance to check with Anubhav on why we need to include ShouldCreateIdentity?

2023-04-13 18:21 UTC, nikkomiu commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/preview/2023-05-01-preview/examples/GetExtensionType.json
> +          "shouldCreateIdentity": true,
Yea, this is something that partner teams were looking for when using the CLI so they could determine if they're going to need the identity. Right now they have to do some weird hacky things to get it working properly and he'd really like this property to be added for the API.

2023-04-13 18:22 UTC, nikkomiu commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/preview/2023-05-01-preview/examples/GetExtensionTypeVersion.json
> +            "appliances": [
Yea, that's what we'll do. But if they don't specify a cluster type we'll show all unsupported versions for all cluster types.

2023-04-13 20:44 UTC, RamyasreeChakka commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/preview/2023-05-01-preview/extensionTypes.json
> +            "description": "Filter results by Offer ID of a marketplace extension type",
>Filter results by Offer ID of a marketplace extension type [](http://example.com/codeflow?start=28&length=58)

Please use below text
Filter results by Offer ID or Product ID of a marketplace extension type"

2023-04-13 20:45 UTC, nikkomiu commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/preview/2023-05-01-preview/extensionTypes.json
> +            "description": "Filter results by Offer ID of a marketplace extension type",
This doesn't do both. This field only filters for the Offer ID. The productId field filters for the Product ID.

2023-04-13 20:48 UTC, RamyasreeChakka commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/preview/2023-05-01-preview/extensionTypes.json
> +            "description": "Filter results by Offer ID of a marketplace extension type",
>Filter results by Offer ID of a marketplace extension type [](http://example.com/codeflow?start=28&length=58)

Filter results by Offer ID or Product ID of a marketplace extension type"

2023-04-13 20:50 UTC, nikkomiu commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/preview/2023-05-01-preview/extensionTypes.json
> +                "description": "Offer ID of the Marketplace Extension Type."
I only need one of these. When they're the same thing I just bulk update them all.

2023-04-13 20:56 UTC, RamyasreeChakka commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/preview/2023-05-01-preview/examples/GetExtensionType.json
> +        "properties": {
When you submit the pull request to ARM rest api specs repo, I think you may run into a check which validates the GET reponses follow the ARM resource model. 

In this model, I see you have properties but do not have top level properties like id, name, type.

2023-04-13 21:02 UTC, RamyasreeChakka commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/preview/2023-05-01-preview/examples/GetExtensionTypeByLocation.json
> +          "properties": {
Why does this response contain 'value'? 
Get on a specific extension type should return only single object similar to GetExtensionType.json example

2023-04-13 21:04 UTC, RamyasreeChakka commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/preview/2023-05-01-preview/examples/GetExtensionTypeVersionByLocation.json
> +          "version": "1.1.0",
Use 'value' property for only list responses i.e. when the URI has odd number of segments.

2023-04-13 21:30 UTC, nikkomiu commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/preview/2023-05-01-preview/examples/GetExtensionType.json
> +        "properties": {
They're in there now

2023-04-13 21:44 UTC, RamyasreeChakka approved these changes
:shipit:

2023-04-13 22:09 UTC, ponatara commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/preview/2023-05-01-preview/examples/GetExtensionType.json
> +          "shouldCreateIdentity": true,
I spoke to Anubhav. Can we rename this property to be more user-friendly -"isManagedIdentityRequired": true 
Summarizing discussion for everyone - Some solutions need a MI (like Azure backup, Azure Monitor). ARM creates the identity in user's tenant. Our RP cannot do that, so this intent has to come through the ARM API (which we have today). Exposing this as part of this API will make it apparent to customers that some extensions need identity and customers can pass it if using REST API

2023-04-14 14:10 UTC, nikkomiu commented on specification/kubernetesconfiguration/resource-manager/Microsoft.KubernetesConfiguration/preview/2023-05-01-preview/examples/GetExtensionType.json
> +          "shouldCreateIdentity": true,
Done

2023-04-14 14:40 UTC, ponatara approved these changes

2023-04-15 19:57 UTC, merged